In [9]:
import pandas as pd
import numpy as np

In [10]:
# Loading cleaned dataset from previous notebook
df = pd.read_csv(r"C:/Users/BIT/Desktop/AIML ASSIGNMENT/data/cleaned_daily_water_consumption.csv")

# Convert Date again (important after reload)
df['Date'] = pd.to_datetime(df['Date'])

df.head()

,Date,Person_ID,Age,Gender,City,Temperature_C,Activity_Level,Water_Consumed_Liters,Consumption_scaled
0,2025-01-01,P0053,27.0,Female,Karachi,40.5,High,3.76,0.857143
1,2025-01-01,P0069,41.0,Female,Rawalpindi,18.6,Medium,2.40,0.383275
2,2025-01-01,P0070,48.0,Female,Lahore,28.5,Medium,2.83,0.533101
3,2025-01-01,P0061,41.0,Female,Karachi,17.7,Low,1.76,0.160279
4,2025-01-01,P0062,40.0,Male,Multan,30.2,High,3.40,0.731707

In [11]:
# Extracting useful time features

df['Day'] = df['Date'].dt.day
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year
df['Day_of_Week'] = df['Date'].dt.dayofweek  # 0 = Monday

df.head()

,Date,Person_ID,Age,Gender,City,Temperature_C,Activity_Level,Water_Consumed_Liters,Consumption_scaled,Day,Month,Year,Day_of_Week
0,2025-01-01,P0053,27.0,Female,Karachi,40.5,High,3.76,0.857143,1,1,2025,2
1,2025-01-01,P0069,41.0,Female,Rawalpindi,18.6,Medium,2.40,0.383275,1,1,2025,2
2,2025-01-01,P0070,48.0,Female,Lahore,28.5,Medium,2.83,0.533101,1,1,2025,2
3,2025-01-01,P0061,41.0,Female,Karachi,17.7,Low,1.76,0.160279,1,1,2025,2
4,2025-01-01,P0062,40.0,Male,Multan,30.2,High,3.40,0.731707,1,1,2025,2

In [12]:
# Rolling average (smooth trend)
df['Rolling_Mean_3'] = df['Water_Consumed_Liters'].rolling(window=3).mean()

# Rolling standard deviation (variation)
df['Rolling_Std_3'] = df['Water_Consumed_Liters'].rolling(window=3).std()

In [13]:
# Removing initial rows with NaN due to rolling
df = df.dropna()

df.head()

,Date,Person_ID,Age,Gender,City,Temperature_C,Activity_Level,Water_Consumed_Liters,Consumption_scaled,Day,Month,Year,Day_of_Week,Rolling_Mean_3,Rolling_Std_3
2,2025-01-01,P0070,48.0,Female,Lahore,28.500000,Medium,2.83,0.533101,1,1,2025,2,2.996667,0.695150
3,2025-01-01,P0061,41.0,Female,Karachi,17.700000,Low,1.76,0.160279,1,1,2025,2,2.330000,0.538424
4,2025-01-01,P0062,40.0,Male,Multan,30.200000,High,3.40,0.731707,1,1,2025,2,2.663333,0.832606
5,2025-01-01,P0063,57.0,Female,Rawalpindi,25.800000,Low,2.31,0.351916,1,1,2025,2,2.490000,0.834686
6,2025-01-01,P0100,55.0,Male,Rawalpindi,28.541075,Medium,2.40,0.383275,1,1,2025,2,2.703333,0.605007

In [14]:
# Previous day's consumption
df['Lag_1'] = df['Water_Consumed_Liters'].shift(1)

# Removing NaN created due to lag
df = df.dropna()

In [15]:
# Converting categorical variables to numeric

df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})

df['Activity_Level'] = df['Activity_Level'].map({
    'Low': 0,
    'Medium': 1,
    'High': 2
})

In [16]:
# One-hot encoding for City
# Helps model understand location differences
df = pd.get_dummies(df, columns=['City'], drop_first=True)

In [17]:
# Displaying final columns
print("Final features:\n", df.columns)

# Shape of dataset
print("\nShape after feature engineering:", df.shape)

Final features:
 Index(['Date', 'Person_ID', 'Age', 'Gender', 'Temperature_C', 'Activity_Level',
       'Water_Consumed_Liters', 'Consumption_scaled', 'Day', 'Month', 'Year',
       'Day_of_Week', 'Rolling_Mean_3', 'Rolling_Std_3', 'Lag_1',
       'City_Islamabad', 'City_Karachi', 'City_Lahore', 'City_Multan',
       'City_Rawalpindi'],
      dtype='str')

Shape after feature engineering: (32901, 20)

In [18]:
# Saving dataset for next step (anomaly detection)

df.to_csv("C:/Users/BIT/Desktop/AIML ASSIGNMENT/data/feature_engineered_data.csv", index=False)

print("Feature engineered dataset saved successfully!")

Feature engineered dataset saved successfully!